### ISSUE TITLE
gogs二进制包下载路径需要规范

### ISSUE THREAD

**Issue by jingwu15** [gogs/docs#184]
在二进制包下载页面，点击下载连接，指向链接地址是：https://dl.gogs.io/0.11.34/linux_386.tar.gz
文件名： linux_386.tar.gz 很容易产生误导，应用更规范化的名称，如：gogs-386-0.11.34.tar.gz

**Comment by Unknwon** [comment]
有道理啊！

**Comment by Unknwon** [comment]
最近几版已经改好啦
