### ISSUE TITLE
Incorrect 'user filter' definition for ldap with BindDN

### ISSUE THREAD

**Issue by 4abhinavjain** [gogs/docs#227]
Hi,

I struggled a lot to make my LDAP login work. I want to use both mail and well as uid for login. The document highlight to use the following user filter for BindDN:

(&(objectClass=Person)(|(uid=%[1]s)(mail=%[1]s)(mobile=%[1]s)))

However, %[1]s is not working and plain %s is working:
(&(objectClass=Person)(|(uid=%s)(mail=%]s)(mobile=%s)))

Can someone please confirm and update? I wasted almost 4 hours because of it.

My gogs version is: 0.11.86.0130 and Go: 1.10.2

Thanks,
AJ

**Comment by Unknwon** [comment]
Hi, thanks for the feedback!

After some digging, I believe you're right about this. Sorry about inconsistency!

I have fixed docs accordingly.

**Comment by 4abhinavjain** [comment]
Hi,

Thanks for looking into this.

Best rgds,
AJ
