### ISSUE TITLE
FreeIPA authentication much simpler

### ISSUE THREAD

**Issue by zwets** [gogs/docs#237]
The description of using FreeIPA for authentication on https://gogs.io/docs/features/authentication can be much simplified. As FreeIPA allows anonymous queries, there is no need for creating a BindDN user.

Instead, the following settings suffice:

- Authentication Type: **LDAP (via BindDN)**
- Security Protocol: **LDAPS** (or StartTLS, but then port 389)
- Host: **_ipa.your.domain_**
- Port: **636** (or 389 for StartTLS)
- Bind DN: _leave empty (anonymous search)_
- Bind Password: _leave empty_
- User Search Base: `cn=users,cn=accounts,dc=your,dc=domain`
- User Filter: `(&(objectClass=posixAccount)(uid=%s))`
- Admin Filter: `(memberOf=cn=admins,cn=groups,cn=accounts,dc=your,dc=domain)`
- Attributes: `uid`, `givenName`, `sn`, `mail`

See https://github.com/gogs/gogs/issues/5025#issuecomment-532188975 for background.

**Comment by unknwon** [comment]
Thanks for the info! Would you mind send a PR for these changes?

**Comment by zwets** [comment]
Looking deeper, it turned out to be _yet_ simpler. Unfortunately it's never as easy to write it down.
